
language: python

python :
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - coverage report

after_success:
  - nosetests --with-coverage --cover-package=source/routes
  - coveralls

notifications:
  slack:
    on_success: never
    on_failure: never
  email: false
