
language: python

python :
  - "3.6"
install:
  - pip install -r requirements.txt
script: 
  - cd ./tests && nosetests
after_success: 
  - coveralls

notifications:
  slack:
    on_success: never
    on_failure: never
  email: false
