FORMAT: 1A
HOST: http://weconnect-api-heroku.herokuapp.com

# WeConnect
WeConnect provides a platform that brings businesses and individuals together.
This platform creates awareness for businesses and gives the users the
ability to write reviews about the businesses they have interacted with.

# Group User

## User Registration [/api/v1/auth/register]
All requests sent by client to register new user accounts are handled by
this resource. Receives data in `json` format and it should check that
all the required fields are supplied.

### Register a user [POST]
The Endpoint registers a new Business
+ Request (application/json)
Request is sent with the user details in `json` format after validation
            
    - Body
        
            {
                "email": "james@gmail.com"
                "username":"james7738"
                "password":"thisisandela123"
            }
    
+ Response 200 (application/json)
Returns response when all user data is validated.
    - Headers
        
            
    - Body 
                
            {
                "message": "user registered"
            }
            
+ Response 401 (applicaton/json)
Returns response when the email passed in request is found in the database.   
    - Headers
    
    - Body 
            
            {
                "message": "Email already registered"
            }

## User Login [/api/v1/auth/login]
All requests sent by client to login a user account are handled by
this resource. Receives data in `json` format and it should check that
all the required fields are supplied.

### Login a user [POST]
Enpoint which logs in the user.
+ Request (application/json)
The request carries the user data passed in `json` format after validation

    - Headers
    
    - Body
    
            {
                "email": "james@gmail.com"
                "password":"thisisandela123"
            }

+ Response 201 (application/json)
Returns a tokenstring upon validating user input
    - Headers
        
            
    - Body 
                
            {
                "token": "tokenstring"
            }  
    




## Business Registration [/api/v1/business/]
All requests sent by client to register new Business accounts are handled by
this resource. Receives data in `json` format and it should check that
all the required fields are supplied.


### Register Business [POST]
registers a new business
+ Request (application/json)
The request carries business deatails in `json` format after validating the inputs.

    - Headers

            Auhtorization : Bearer tokenstring
            
    - Body
        
            {
                "businessname": "techbase",
                "Description":"james7738",
                "category":"thisisandela123",
                "location":"runda"
            }
    
+ Response 201 (application/json)
Returns a `json` success message upon validating the user input.
    - Headers
        
            
    - Body 
                
            {
                "message": "Business successfully registered"
            }
            
+ Response 409 (application/json)
Returns a  json `json` message  
    - Headers
        
            
    - Body 
                
            {
                "message": "Business already exists"
            }
            
                
### Get Business [GET]
Resquest sent to this resource returns all the businesses in the database.
            
    
+ Response 200 (application/json)
Returns `json` objects upon sending the get request.

    - Headers 

            
    - Body 
                
            {
                "businessname": "techbase"
                "Description":"james7738"
                "category":"thisisandela123"
                "location":"runda"
            }
    



## Single Business [/api/v1/business/{id}]
All requests are  that  sent by the client retrieves a single Business account are handled by
this resource. Receives data in `json` format and it should check that
all the required fields are supplied.

+ Parameters
    - id: 1 (string) - the id of the business
    

### Get Business [GET]
Resquest sent to this resource returns all the businesses in the database.
            
    
+ Response 200 (application/json)
Returns `json` object upon  sending the get request for a specific business.

    - Headers 

            
    - Body 
                
            {
                "businessname": "techbase"
                "Description":"james7738"
                "category":"thisisandela123"
                "location":"runda"
            }
    

### Update Business[PUT]
This enpoint updates the business.
+ Request (application/json)
Request takes a token header and business 
    - Header 
            
            Authorization: Bearer tokenstring
            

            
    - Body
        
            {
                "businessname": "techbase"
                "Description":"james7738"
                "category":"thisisandela123"
                "location":"runda"
            }
    
+ Response 200 (application/json)
Returns a `json` updated request of the post request sent.
    - Headers
        
            
    - Body 
                
            {
                "businessname": "techbase",
                "Description":"james7738",
                "category":"thisisandela123",
                "location":"runda"
            }

### Delete Business[DELETE]
This endpoint deletes a business.
+ Response 202 (application/json)
deletes a business upon validating the token passed in the headers.

    - Headers

                Authorization: Bearer tokenstring
             
    - Body 
                
            {
                "message":"Business successfully deleted"
            }
            
+ Response 404 (application/json)
Returnes when a queried business is not found in the database.   
    - Headers
               
    - Body 
                
            {
                "message":"Business not found"
            }
            
## Logout [/api/v1/auth/logout]
Requests sent by the client to this resource dumps the current token and renders it invalid.


### Logout User[DELETE]
The endpoint logs out a user

+ Response 200 (application/json)
returns  a success `json` message after invalidating the token.
            
    - Body 
                
            {
                "message":"Successfully logged out"
            }