"""empty message

Revision ID: 4cbe71a46b4e
Revises: 74ce553b8441
Create Date: 2018-03-30 12:01:38.418887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbe71a46b4e'
down_revision = '74ce553b8441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'business', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'business_id')
    # ### end Alembic commands ###
