"""empty message

Revision ID: 61686c847561
Revises: 4cbe71a46b4e
Create Date: 2018-03-30 13:40:52.099078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61686c847561'
down_revision = '4cbe71a46b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('business_category_key', 'business', type_='unique')
    op.drop_constraint('business_description_key', 'business', type_='unique')
    op.drop_constraint('business_location_key', 'business', type_='unique')
    op.drop_constraint('reviews_review_key', 'reviews', type_='unique')
    op.drop_constraint('reviews_title_key', 'reviews', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('reviews_title_key', 'reviews', ['title'])
    op.create_unique_constraint('reviews_review_key', 'reviews', ['review'])
    op.create_unique_constraint('business_location_key', 'business', ['location'])
    op.create_unique_constraint('business_description_key', 'business', ['description'])
    op.create_unique_constraint('business_category_key', 'business', ['category'])
    # ### end Alembic commands ###
