"""empty message

Revision ID: ed66ef29ebd1
Revises: 2e088ad0bb4e
Create Date: 2018-04-04 15:43:30.686193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed66ef29ebd1'
down_revision = '2e088ad0bb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cpassword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpassword', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
